// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.1
// source: proto/bank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankAccountType int32

const (
	BankAccountType_SAVINGS  BankAccountType = 0
	BankAccountType_CHECKING BankAccountType = 1
)

// Enum value maps for BankAccountType.
var (
	BankAccountType_name = map[int32]string{
		0: "SAVINGS",
		1: "CHECKING",
	}
	BankAccountType_value = map[string]int32{
		"SAVINGS":  0,
		"CHECKING": 1,
	}
)

func (x BankAccountType) Enum() *BankAccountType {
	p := new(BankAccountType)
	*p = x
	return p
}

func (x BankAccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BankAccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_proto_enumTypes[0].Descriptor()
}

func (BankAccountType) Type() protoreflect.EnumType {
	return &file_proto_bank_proto_enumTypes[0]
}

func (x BankAccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BankAccountType.Descriptor instead.
func (BankAccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_proto_rawDescGZIP(), []int{0}
}

type BankAccountStatus int32

const (
	BankAccountStatus_INACTIVE BankAccountStatus = 0
	BankAccountStatus_ACTIVE   BankAccountStatus = 1
)

// Enum value maps for BankAccountStatus.
var (
	BankAccountStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
	}
	BankAccountStatus_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
	}
)

func (x BankAccountStatus) Enum() *BankAccountStatus {
	p := new(BankAccountStatus)
	*p = x
	return p
}

func (x BankAccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BankAccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_proto_enumTypes[1].Descriptor()
}

func (BankAccountStatus) Type() protoreflect.EnumType {
	return &file_proto_bank_proto_enumTypes[1]
}

func (x BankAccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BankAccountStatus.Descriptor instead.
func (BankAccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_proto_rawDescGZIP(), []int{1}
}

var File_proto_bank_proto protoreflect.FileDescriptor

var file_proto_bank_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x2a, 0x2c, 0x0a, 0x0f, 0x42, 0x61, 0x6e, 0x6b,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x41, 0x56, 0x49, 0x4e, 0x47, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x48, 0x45, 0x43,
	0x4b, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x2a, 0x2d, 0x0a, 0x11, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x49,
	0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54,
	0x49, 0x56, 0x45, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bank_proto_rawDescOnce sync.Once
	file_proto_bank_proto_rawDescData = file_proto_bank_proto_rawDesc
)

func file_proto_bank_proto_rawDescGZIP() []byte {
	file_proto_bank_proto_rawDescOnce.Do(func() {
		file_proto_bank_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bank_proto_rawDescData)
	})
	return file_proto_bank_proto_rawDescData
}

var file_proto_bank_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_bank_proto_goTypes = []interface{}{
	(BankAccountType)(0),   // 0: bank.BankAccountType
	(BankAccountStatus)(0), // 1: bank.BankAccountStatus
}
var file_proto_bank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_proto_init() }
func file_proto_bank_proto_init() {
	if File_proto_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bank_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_proto_goTypes,
		DependencyIndexes: file_proto_bank_proto_depIdxs,
		EnumInfos:         file_proto_bank_proto_enumTypes,
	}.Build()
	File_proto_bank_proto = out.File
	file_proto_bank_proto_rawDesc = nil
	file_proto_bank_proto_goTypes = nil
	file_proto_bank_proto_depIdxs = nil
}
