// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.1
// source: proto/bank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankStatus int32

const (
	BankStatus_IS_INACTIVE BankStatus = 0
	BankStatus_IS_ACTIVE   BankStatus = 1
)

// Enum value maps for BankStatus.
var (
	BankStatus_name = map[int32]string{
		0: "IS_INACTIVE",
		1: "IS_ACTIVE",
	}
	BankStatus_value = map[string]int32{
		"IS_INACTIVE": 0,
		"IS_ACTIVE":   1,
	}
)

func (x BankStatus) Enum() *BankStatus {
	p := new(BankStatus)
	*p = x
	return p
}

func (x BankStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BankStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_proto_enumTypes[0].Descriptor()
}

func (BankStatus) Type() protoreflect.EnumType {
	return &file_proto_bank_proto_enumTypes[0]
}

func (x BankStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BankStatus.Descriptor instead.
func (BankStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_proto_rawDescGZIP(), []int{0}
}

type BankType int32

const (
	BankType_NOT_FOUND BankType = 0
	BankType_CHECKING  BankType = 1
	BankType_SAVINGS   BankType = 2
)

// Enum value maps for BankType.
var (
	BankType_name = map[int32]string{
		0: "NOT_FOUND",
		1: "CHECKING",
		2: "SAVINGS",
	}
	BankType_value = map[string]int32{
		"NOT_FOUND": 0,
		"CHECKING":  1,
		"SAVINGS":   2,
	}
)

func (x BankType) Enum() *BankType {
	p := new(BankType)
	*p = x
	return p
}

func (x BankType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BankType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bank_proto_enumTypes[1].Descriptor()
}

func (BankType) Type() protoreflect.EnumType {
	return &file_proto_bank_proto_enumTypes[1]
}

func (x BankType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BankType.Descriptor instead.
func (BankType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bank_proto_rawDescGZIP(), []int{1}
}

var File_proto_bank_proto protoreflect.FileDescriptor

var file_proto_bank_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x2a, 0x2c, 0x0a, 0x0a, 0x42, 0x61, 0x6e, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x53, 0x5f, 0x49, 0x4e, 0x41,
	0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x53, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x2a, 0x34, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x41, 0x56, 0x49, 0x4e, 0x47, 0x53, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bank_proto_rawDescOnce sync.Once
	file_proto_bank_proto_rawDescData = file_proto_bank_proto_rawDesc
)

func file_proto_bank_proto_rawDescGZIP() []byte {
	file_proto_bank_proto_rawDescOnce.Do(func() {
		file_proto_bank_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bank_proto_rawDescData)
	})
	return file_proto_bank_proto_rawDescData
}

var file_proto_bank_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_bank_proto_goTypes = []interface{}{
	(BankStatus)(0), // 0: bank.BankStatus
	(BankType)(0),   // 1: bank.BankType
}
var file_proto_bank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_proto_init() }
func file_proto_bank_proto_init() {
	if File_proto_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bank_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_proto_goTypes,
		DependencyIndexes: file_proto_bank_proto_depIdxs,
		EnumInfos:         file_proto_bank_proto_enumTypes,
	}.Build()
	File_proto_bank_proto = out.File
	file_proto_bank_proto_rawDesc = nil
	file_proto_bank_proto_goTypes = nil
	file_proto_bank_proto_depIdxs = nil
}
